version: '3'    
services:
    db:
      image: postgres
      environment:
        - POSTGRES_DB=postgres_db
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
    web:
      build: .
      command: gunicorn composeexample.wsgi:application --bind 0.0.0.0:8000
      volumes:
        - .:/code
      ports:
        - "8000:8000"
      env_file:
        - .env
      depends_on:
        - db
